version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-app
    restart: unless-stopped
    networks:
      - chat_network
    ports:
      - '3078:3078'
    depends_on:
      - redis
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules

  redis:
    image: 'redis:6.2'
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - chat_network



  mongodb:
    image: mongo:latest
    container_name: my-mongodb-chat
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=chat-app
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongodb:/data/db
    networks:
      - chat_network

  mongo-express:
    image: mongo-express:latest
    container_name: my-mongo-express

    restart: always
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - chat_network
    depends_on:
      - mongodb

volumes:
  mongo-data:
    driver: local

networks:
  chat_network:
    driver: bridge